# Generated by Django 6.0.3 on 2026-04-05 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachments/%Y/%m/')),
                ('external_url', models.URLField(blank=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('slide', 'Slide'), ('note', 'Note'), ('link', 'External Link'), ('other', 'Other')], default='other', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments_new', to='courses.contentnode')),
            ],
        ),
    ]
