# Generated by Django 6.0.3 on 2026-04-05 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The question text')),
                ('image', models.ImageField(blank=True, null=True, upload_to='qa/question_images/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='qa/question_pdfs/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='qa/question_audio/')),
                ('answer_type', models.CharField(blank=True, choices=[('ai', 'AI Teacher'), ('human', 'Human Teacher')], help_text='Set after modal choice', max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ai_answered', 'AI Answered'), ('answered', 'Answered')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to='courses.course')),
                ('subject', models.ForeignKey(blank=True, help_text='Top-level subject node (optional)', limit_choices_to={'parent__isnull': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_questions', to='courses.contentnode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QAAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ai', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='qa/answer_images/')),
                ('audio', models.FileField(blank=True, null=True, upload_to='qa/answer_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responder', models.ForeignKey(blank=True, help_text='Null for AI answers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qa_answers', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qa.qaquestion')),
            ],
            options={
                'verbose_name': 'Answer',
                'ordering': ['created_at'],
            },
        ),
    ]
