# Generated by Django 6.0.3 on 2026-04-11 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='topic',
            field=models.ForeignKey(blank=True, help_text='Topic node this exam belongs to (optional)', limit_choices_to={'node_type': 'topic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_exams', to='courses.contentnode'),
        ),
    ]
