# Generated by Django 6.0.3 on 2026-04-13 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_examattempt_correct_answers_examattempt_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolveSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='solve_sheets/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_sheets', to='courses.course')),
                ('subject', models.ForeignKey(help_text='Top-level subject node this solve sheet belongs to', limit_choices_to={'parent__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_solve_sheets', to='courses.contentnode')),
                ('topic', models.ForeignKey(blank=True, help_text='Topic node this solve sheet belongs to (optional)', limit_choices_to={'node_type': 'topic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_solve_sheets', to='courses.contentnode')),
            ],
            options={
                'verbose_name': 'Solve Sheet',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
