# Generated by Django 6.0.3 on 2026-04-20 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_solvesheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='batch_year',
            field=models.CharField(blank=True, help_text='e.g. 2026', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, help_text='Subject type e.g. Science', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price in BDT', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='what_you_will_learn',
            field=models.TextField(blank=True, help_text='One item per line or HTML'),
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='courses.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
