# Generated by Django 6.0.3 on 2026-06-05 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_course_instructor_course_instructors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('total_active_days', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Streak',
            },
        ),
        migrations.CreateModel(
            name='StreakBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_required', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('streak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='courses.studentstreak')),
            ],
            options={
                'verbose_name': 'Streak Badge',
                'ordering': ['days_required'],
                'unique_together': {('streak', 'days_required')},
            },
        ),
    ]
