# Generated by Django 6.0.3 on 2026-06-07 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_streak_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('notes', 'Notes'), ('flashcards', 'Flashcards'), ('mcqs', 'MCQs'), ('summary', 'Summary'), ('next_topics', 'Next Topics')], max_length=20)),
                ('content', models.JSONField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_contents', to='courses.contentnode')),
            ],
            options={
                'verbose_name': 'AI Content',
                'ordering': ['-updated_at'],
                'unique_together': {('node', 'content_type')},
            },
        ),
    ]
