# Generated by Django 6.0.3 on 2026-06-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_ai_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('board_name', models.CharField(choices=[('Dhaka', 'Dhaka'), ('Rajshahi', 'Rajshahi'), ('Cumilla', 'Cumilla'), ('Jashore', 'Jashore'), ('Chattogram', 'Chattogram'), ('Barishal', 'Barishal'), ('Sylhet', 'Sylhet'), ('Dinajpur', 'Dinajpur'), ('Mymensingh', 'Mymensingh')], max_length=50)),
                ('year', models.IntegerField(help_text='Exam Year')),
                ('exam_type', models.CharField(choices=[('Written', 'Written'), ('MCQ', 'MCQ')], max_length=20)),
                ('pdf_file', models.FileField(upload_to='board_questions/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Board Question',
                'ordering': ['-year', 'board_name', 'title'],
            },
        ),
    ]
