# Generated by Django 6.0.3 on 2026-06-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_boardquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('provider', models.CharField(help_text='Organisation or government offering the scholarship', max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('local', 'Local'), ('international', 'International')], default='local', max_length=20)),
                ('level', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('any', 'Any Level')], default='any', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='open', max_length=20)),
                ('benefits', models.TextField(help_text='What students receive (stipend, tuition, airfare, etc.)')),
                ('description', models.TextField(help_text='Full details about the scholarship')),
                ('eligibility', models.TextField(blank=True, help_text='Who can apply')),
                ('apply_url', models.URLField(blank=True, help_text='External application link')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('icon', models.CharField(default='fas fa-graduation-cap', help_text='FontAwesome icon class', max_length=100)),
                ('color_class', models.CharField(default='blue', help_text='Colour theme: blue, green, purple, orange, red, teal', max_length=30)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Scholarship',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScholarshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, help_text='Why do you want to apply for this scholarship?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='courses.scholarship')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Scholarship Application',
                'ordering': ['-applied_at'],
                'unique_together': {('scholarship', 'user')},
            },
        ),
    ]
