# Generated by Django 6.0.3 on 2026-04-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('text', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating 1-5')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
